[workspace]
authors = ["Josiah Laivins <jklaivins@gmail.com>"]
channels = [
    "https://conda.modular.com/max-nightly", 
    "https://repo.prefix.dev/modular-community", 
    "conda-forge"
]
name = "mav"
platforms = ["linux-64", "linux-aarch64"]
version = "0.0.1"
license = "Apache-2.0"
license-file = "LICENSE"
homepage = "https://github.com/josiahls/mav"
repository = "https://github.com/josiahls/mav"

[environments]
stdlib-dev = {features = ["stdlib-dev"]}

[dependencies]
mojo = "==0.26.2.0.dev2026031005,<0.27"
pre-commit = ">=4.5.0,<5"

[activation.env]
MAV_INCLUDES = " -I . -I third_party/NuMojo"
MAV_SO_INSTALL_PREFIX = "$PIXI_PROJECT_ROOT/third_party/ffmpeg/build/lib"
LIBRARY_PATH = "$PIXI_PROJECT_ROOT/third_party/ffmpeg/build/lib:$LIBRARY_PATH"
LD_LIBRARY_PATH = "$PIXI_PROJECT_ROOT/third_party/ffmpeg/build/lib:$LD_LIBRARY_PATH"
MAV_LINKERS = " -Xlinker -lavutil -Xlinker -lavcodec -Xlinker -lswresample -Xlinker -lswscale -Xlinker -lavformat"
MOJO_ENABLE_STACK_TRACE_ON_ERROR="1"
LOGGING_LEVEL="DEBUG"

[tasks]
########################## Pre-commit Configuration ############################
install_pre_commit_hooks = { cmd = [
    "pre-commit", "install"
], outputs = [".git/hooks/pre-commit"]}

# Note: This should be in the third_party setup directory, but pixi's support
# for outputs in its written out form isn't supported.
build_ffmpeg = { cmd = "bash tools/build_ffmpeg.sh", inputs = [
    "tools/build_ffmpeg.sh",
], outputs = [
    "third_party/ffmpeg/build/lib/*.so"
], depends-on = [ "clone_ffmpeg", "install_libopenh264" ] }

# Same as above, however will run every time.
build_ffmpeg_clean = { cmd = "FORCE_FFMPEG_BUILD=true bash tools/build_ffmpeg.sh", depends-on = [ "clone_ffmpeg", "install_libopenh264" ] }

############################ Git Ops ###########################################
push = "git push --force-with-lease"

[tasks.rebase]
cmd = "git rebase -i HEAD~{{ n_commits }}"
args = [{ arg = "n_commits", default = "1" }]

######################### Third Party Setup API ################################

[tasks.clone_ffmpeg]
cmd = "bash tools/clone_ffmpeg.sh"

[tasks.install_libopenh264]
cmd = "bash tools/install_libopenh264.sh"

############################### Env setup ######################################

[tasks.configure_lldb]
cmd = "bash tools/configure_lldb.sh"

######################## Test Data Generation API ##############################
[tasks.generate_test_videos]
cmd = "bash tools/generate_test_videos.sh"

############################### Core API #######################################
[tasks.configure]
cmd = "bash tools/configure.sh"
depends-on = [ "install_pre_commit_hooks", "build_ffmpeg", "generate_test_videos", "install_libopenh264" ]

[tasks.package]
cmd = "pixi run mojo package $MAV_INCLUDES mav"
depends-on = [ "configure" ]

[tasks.build]
cmd = "pixi run mojo build $MAV_LINKERS $MAV_INCLUDES {{ file }} -o $(tools/mojo_build_ex.sh {{ file }})"
args = ["file"]

[tasks.build_debug]
cmd = "pixi run mojo build $MAV_LINKERS $MAV_INCLUDES --debug-level=line-tables {{ file }} -o $(tools/mojo_build_ex.sh {{ file }})"
args = ["file"]

[tasks.build_valgrind]
cmd = "pixi run mojo build $MAV_LINKERS $MAV_INCLUDES --debug-level=line-tables {{ file }} --march=x86-64-v2 -o $(tools/mojo_build_ex.sh {{ file }})"
args = ["file"]

[tasks.build_sanitize]
cmd = "pixi run mojo build $MAV_LINKERS $MAV_INCLUDES --debug-level=line-tables {{ file }} --sanitize=address -o $(tools/mojo_build_ex.sh {{ file }})"
args = ["file"]

[tasks.format]
cmd = "pixi run mojo format mav"

[tasks.test_no_config]
cmd = "./$(tools/mojo_build_ex.sh {{ file }})"
args = ["file"]
depends-on = [ { task = "build_debug", args = ["{{ file }}"] } ]

[tasks.valgrind]
cmd = "valgrind --leak-check=full --track-origins=yes -s $(tools/mojo_build_ex.sh {{ file }})"
args = ["file"]
depends-on = [ { task = "build_valgrind", args = ["{{ file }}"] } ]

[tasks.debug]
cmd = "pixi run mojo debug ./$(tools/mojo_build_ex.sh {{ file }})"
args = ["file"]
depends-on = [ "configure_lldb" ]

[tasks.test]
args = ["file"]
depends-on = [ 
    "configure",  
    { task = "test_no_config", args = ["{{ file }}"] }
]

[tasks.test_all]
cmd = "pixi run mojo run run_tests.mojo"
depends-on = [ "configure" ]

########################## Mojo Standard Library ###############################
[feature.stdlib-dev.activation.env]
MODULAR_MOJO_MAX_IMPORT_PATH="$PIXI_PROJECT_ROOT/third_party/modular/bazel-bin"
# MOJO_ENABLE_STACK_TRACE_ON_ERROR="1"

[feature.stdlib-dev.tasks]
clone_stdlib = "bash tools/clone_stdlib.sh"

sym_link_stdlib = "bash tools/sym_link_stdlib.sh"

update_stdlib = { cmd = [
    "cd", "third_party/modular", "&&",
    "./bazelw", "build", "//mojo/stdlib/std"
], depends-on = [ "sym_link_stdlib", "clone_stdlib" ]}

clean_update_stdlib = { cmd = [
    "cd", "third_party/modular", "&&",
    "git", "switch", "main", "&&",
    "git", "fetch", "origin", "&&",
    "git", "reset", "--hard", "origin/main", "&&",
    "./bazelw", "build", "//mojo/stdlib/..."
], depends-on = [ "clone_stdlib" ]}
