"See https://www.ffmpeg.org/doxygen/8.0/codec__id_8h.html."
from std.ffi import c_int

from mav.ffmpeg.avcodec.version_major import (
    FF_API_V408_CODECID,
    FF_API_INIT_PACKET,
    FF_API_CODEC_PROPS,
    FF_API_EXR_GAMMA,
    FF_API_NVDEC_OLD_PIX_FMTS,
    FF_CODEC_OMX,
    FF_CODEC_SONIC_ENC,
    FF_CODEC_SONIC_DEC,
)


@fieldwise_init("implicit")
struct AVCodecID(Movable, Writable):
    "See https://www.ffmpeg.org/doxygen/7.0/group__lavc__core.html#gaadca229ad2c20e060a14fec08a5cc7ce."

    comptime ENUM_DTYPE = c_int

    var _value: Self.ENUM_DTYPE

    @staticmethod
    fn xor(
        value_if_true: Self.ENUM_DTYPE,
        value_if_false: Self.ENUM_DTYPE,
        condition: Bool,
    ) -> Self:
        return Self(value_if_true if condition else value_if_false)

    fn inc(self) -> Self:
        return Self(self._value + 1)

    comptime AV_CODEC_ID_NONE = Self(0)

    # video codecs
    comptime AV_CODEC_ID_MPEG1VIDEO = Self.AV_CODEC_ID_NONE.inc()
    # Below preferred ID for MPEG-1/2 video decoding
    comptime AV_CODEC_ID_MPEG2VIDEO = Self.AV_CODEC_ID_MPEG1VIDEO.inc()
    comptime AV_CODEC_ID_H261 = Self.AV_CODEC_ID_MPEG2VIDEO.inc()
    comptime AV_CODEC_ID_H263 = Self.AV_CODEC_ID_H261.inc()
    comptime AV_CODEC_ID_RV10 = Self.AV_CODEC_ID_H263.inc()
    comptime AV_CODEC_ID_RV20 = Self.AV_CODEC_ID_RV10.inc()
    comptime AV_CODEC_ID_MJPEG = Self.AV_CODEC_ID_RV20.inc()
    comptime AV_CODEC_ID_MJPEGB = Self.AV_CODEC_ID_MJPEG.inc()
    comptime AV_CODEC_ID_LJPEG = Self.AV_CODEC_ID_MJPEGB.inc()
    comptime AV_CODEC_ID_SP5X = Self.AV_CODEC_ID_LJPEG.inc()
    comptime AV_CODEC_ID_JPEGLS = Self.AV_CODEC_ID_SP5X.inc()
    comptime AV_CODEC_ID_MPEG4 = Self.AV_CODEC_ID_JPEGLS.inc()
    comptime AV_CODEC_ID_RAWVIDEO = Self.AV_CODEC_ID_MPEG4.inc()
    comptime AV_CODEC_ID_MSMPEG4V1 = Self.AV_CODEC_ID_RAWVIDEO.inc()
    comptime AV_CODEC_ID_MSMPEG4V2 = Self.AV_CODEC_ID_MSMPEG4V1.inc()
    comptime AV_CODEC_ID_MSMPEG4V3 = Self.AV_CODEC_ID_MSMPEG4V2.inc()
    comptime AV_CODEC_ID_WMV1 = Self.AV_CODEC_ID_MSMPEG4V3.inc()
    comptime AV_CODEC_ID_WMV2 = Self.AV_CODEC_ID_WMV1.inc()
    comptime AV_CODEC_ID_H263P = Self.AV_CODEC_ID_WMV2.inc()
    comptime AV_CODEC_ID_H263I = Self.AV_CODEC_ID_H263P.inc()
    comptime AV_CODEC_ID_FLV1 = Self.AV_CODEC_ID_H263I.inc()
    comptime AV_CODEC_ID_SVQ1 = Self.AV_CODEC_ID_FLV1.inc()
    comptime AV_CODEC_ID_SVQ3 = Self.AV_CODEC_ID_SVQ1.inc()
    comptime AV_CODEC_ID_DVVIDEO = Self.AV_CODEC_ID_SVQ3.inc()
    comptime AV_CODEC_ID_HUFFYUV = Self.AV_CODEC_ID_DVVIDEO.inc()
    comptime AV_CODEC_ID_CYUV = Self.AV_CODEC_ID_HUFFYUV.inc()
    comptime AV_CODEC_ID_H264 = Self.AV_CODEC_ID_CYUV.inc()
    comptime AV_CODEC_ID_INDEO3 = Self.AV_CODEC_ID_H264.inc()
    comptime AV_CODEC_ID_VP3 = Self.AV_CODEC_ID_INDEO3.inc()
    comptime AV_CODEC_ID_THEORA = Self.AV_CODEC_ID_VP3.inc()
    comptime AV_CODEC_ID_ASV1 = Self.AV_CODEC_ID_THEORA.inc()
    comptime AV_CODEC_ID_ASV2 = Self.AV_CODEC_ID_ASV1.inc()
    comptime AV_CODEC_ID_FFV1 = Self.AV_CODEC_ID_ASV2.inc()
    comptime AV_CODEC_ID_4XM = Self.AV_CODEC_ID_FFV1.inc()
    comptime AV_CODEC_ID_VCR1 = Self.AV_CODEC_ID_4XM.inc()
    comptime AV_CODEC_ID_CLJR = Self.AV_CODEC_ID_VCR1.inc()
    comptime AV_CODEC_ID_MDEC = Self.AV_CODEC_ID_CLJR.inc()
    comptime AV_CODEC_ID_ROQ = Self.AV_CODEC_ID_MDEC.inc()
    comptime AV_CODEC_ID_INTERPLAY_VIDEO = Self.AV_CODEC_ID_ROQ.inc()
    comptime AV_CODEC_ID_XAN_WC3 = Self.AV_CODEC_ID_INTERPLAY_VIDEO.inc()
    comptime AV_CODEC_ID_XAN_WC4 = Self.AV_CODEC_ID_XAN_WC3.inc()
    comptime AV_CODEC_ID_RPZA = Self.AV_CODEC_ID_XAN_WC4.inc()
    comptime AV_CODEC_ID_CINEPAK = Self.AV_CODEC_ID_RPZA.inc()
    comptime AV_CODEC_ID_WS_VQA = Self.AV_CODEC_ID_CINEPAK.inc()
    comptime AV_CODEC_ID_MSRLE = Self.AV_CODEC_ID_WS_VQA.inc()
    comptime AV_CODEC_ID_MSVIDEO1 = Self.AV_CODEC_ID_MSRLE.inc()
    comptime AV_CODEC_ID_IDCIN = Self.AV_CODEC_ID_MSVIDEO1.inc()
    comptime AV_CODEC_ID_8BPS = Self.AV_CODEC_ID_IDCIN.inc()
    comptime AV_CODEC_ID_SMC = Self.AV_CODEC_ID_8BPS.inc()
    comptime AV_CODEC_ID_FLIC = Self.AV_CODEC_ID_SMC.inc()
    comptime AV_CODEC_ID_TRUEMOTION1 = Self.AV_CODEC_ID_FLIC.inc()
    comptime AV_CODEC_ID_VMDVIDEO = Self.AV_CODEC_ID_TRUEMOTION1.inc()
    comptime AV_CODEC_ID_MSZH = Self.AV_CODEC_ID_VMDVIDEO.inc()
    comptime AV_CODEC_ID_ZLIB = Self.AV_CODEC_ID_MSZH.inc()
    comptime AV_CODEC_ID_QTRLE = Self.AV_CODEC_ID_ZLIB.inc()
    comptime AV_CODEC_ID_TSCC = Self.AV_CODEC_ID_QTRLE.inc()
    comptime AV_CODEC_ID_ULTI = Self.AV_CODEC_ID_TSCC.inc()
    comptime AV_CODEC_ID_QDRAW = Self.AV_CODEC_ID_ULTI.inc()
    comptime AV_CODEC_ID_VIXL = Self.AV_CODEC_ID_QDRAW.inc()
    comptime AV_CODEC_ID_QPEG = Self.AV_CODEC_ID_VIXL.inc()
    comptime AV_CODEC_ID_PNG = Self.AV_CODEC_ID_QPEG.inc()
    comptime AV_CODEC_ID_PPM = Self.AV_CODEC_ID_PNG.inc()
    comptime AV_CODEC_ID_PBM = Self.AV_CODEC_ID_PPM.inc()
    comptime AV_CODEC_ID_PGM = Self.AV_CODEC_ID_PBM.inc()
    comptime AV_CODEC_ID_PGMYUV = Self.AV_CODEC_ID_PGM.inc()
    comptime AV_CODEC_ID_PAM = Self.AV_CODEC_ID_PGMYUV.inc()
    comptime AV_CODEC_ID_FFVHUFF = Self.AV_CODEC_ID_PAM.inc()
    comptime AV_CODEC_ID_RV30 = Self.AV_CODEC_ID_FFVHUFF.inc()
    comptime AV_CODEC_ID_RV40 = Self.AV_CODEC_ID_RV30.inc()
    comptime AV_CODEC_ID_VC1 = Self.AV_CODEC_ID_RV40.inc()
    comptime AV_CODEC_ID_WMV3 = Self.AV_CODEC_ID_VC1.inc()
    comptime AV_CODEC_ID_LOCO = Self.AV_CODEC_ID_WMV3.inc()
    comptime AV_CODEC_ID_WNV1 = Self.AV_CODEC_ID_LOCO.inc()
    comptime AV_CODEC_ID_AASC = Self.AV_CODEC_ID_WNV1.inc()
    comptime AV_CODEC_ID_INDEO2 = Self.AV_CODEC_ID_AASC.inc()
    comptime AV_CODEC_ID_FRAPS = Self.AV_CODEC_ID_INDEO2.inc()
    comptime AV_CODEC_ID_TRUEMOTION2 = Self.AV_CODEC_ID_FRAPS.inc()
    comptime AV_CODEC_ID_BMP = Self.AV_CODEC_ID_TRUEMOTION2.inc()
    comptime AV_CODEC_ID_CSCD = Self.AV_CODEC_ID_BMP.inc()
    comptime AV_CODEC_ID_MMVIDEO = Self.AV_CODEC_ID_CSCD.inc()
    comptime AV_CODEC_ID_ZMBV = Self.AV_CODEC_ID_MMVIDEO.inc()
    comptime AV_CODEC_ID_AVS = Self.AV_CODEC_ID_ZMBV.inc()
    comptime AV_CODEC_ID_SMACKVIDEO = Self.AV_CODEC_ID_AVS.inc()
    comptime AV_CODEC_ID_NUV = Self.AV_CODEC_ID_SMACKVIDEO.inc()
    comptime AV_CODEC_ID_KMVC = Self.AV_CODEC_ID_NUV.inc()
    comptime AV_CODEC_ID_FLASHSV = Self.AV_CODEC_ID_KMVC.inc()
    comptime AV_CODEC_ID_CAVS = Self.AV_CODEC_ID_FLASHSV.inc()
    comptime AV_CODEC_ID_JPEG2000 = Self.AV_CODEC_ID_CAVS.inc()
    comptime AV_CODEC_ID_VMNC = Self.AV_CODEC_ID_JPEG2000.inc()
    comptime AV_CODEC_ID_VP5 = Self.AV_CODEC_ID_VMNC.inc()
    comptime AV_CODEC_ID_VP6 = Self.AV_CODEC_ID_VP5.inc()
    comptime AV_CODEC_ID_VP6F = Self.AV_CODEC_ID_VP6.inc()
    comptime AV_CODEC_ID_TARGA = Self.AV_CODEC_ID_VP6F.inc()
    comptime AV_CODEC_ID_DSICINVIDEO = Self.AV_CODEC_ID_TARGA.inc()
    comptime AV_CODEC_ID_TIERTEXSEQVIDEO = Self.AV_CODEC_ID_DSICINVIDEO.inc()
    comptime AV_CODEC_ID_TIFF = Self.AV_CODEC_ID_TIERTEXSEQVIDEO.inc()
    comptime AV_CODEC_ID_GIF = Self.AV_CODEC_ID_TIFF.inc()
    comptime AV_CODEC_ID_DXA = Self.AV_CODEC_ID_GIF.inc()
    comptime AV_CODEC_ID_DNXHD = Self.AV_CODEC_ID_DXA.inc()
    comptime AV_CODEC_ID_THP = Self.AV_CODEC_ID_DNXHD.inc()
    comptime AV_CODEC_ID_SGI = Self.AV_CODEC_ID_THP.inc()
    comptime AV_CODEC_ID_C93 = Self.AV_CODEC_ID_SGI.inc()
    comptime AV_CODEC_ID_BETHSOFTVID = Self.AV_CODEC_ID_C93.inc()
    comptime AV_CODEC_ID_PTX = Self.AV_CODEC_ID_BETHSOFTVID.inc()
    comptime AV_CODEC_ID_TXD = Self.AV_CODEC_ID_PTX.inc()
    comptime AV_CODEC_ID_VP6A = Self.AV_CODEC_ID_TXD.inc()
    comptime AV_CODEC_ID_AMV = Self.AV_CODEC_ID_VP6A.inc()
    comptime AV_CODEC_ID_VB = Self.AV_CODEC_ID_AMV.inc()
    comptime AV_CODEC_ID_PCX = Self.AV_CODEC_ID_VB.inc()
    comptime AV_CODEC_ID_SUNRAST = Self.AV_CODEC_ID_PCX.inc()
    comptime AV_CODEC_ID_INDEO4 = Self.AV_CODEC_ID_SUNRAST.inc()
    comptime AV_CODEC_ID_INDEO5 = Self.AV_CODEC_ID_INDEO4.inc()
    comptime AV_CODEC_ID_MIMIC = Self.AV_CODEC_ID_INDEO5.inc()
    comptime AV_CODEC_ID_RL2 = Self.AV_CODEC_ID_MIMIC.inc()
    comptime AV_CODEC_ID_ESCAPE124 = Self.AV_CODEC_ID_RL2.inc()
    comptime AV_CODEC_ID_DIRAC = Self.AV_CODEC_ID_ESCAPE124.inc()
    comptime AV_CODEC_ID_BFI = Self.AV_CODEC_ID_DIRAC.inc()
    comptime AV_CODEC_ID_CMV = Self.AV_CODEC_ID_BFI.inc()
    comptime AV_CODEC_ID_MOTIONPIXELS = Self.AV_CODEC_ID_CMV.inc()
    comptime AV_CODEC_ID_TGV = Self.AV_CODEC_ID_MOTIONPIXELS.inc()
    comptime AV_CODEC_ID_TGQ = Self.AV_CODEC_ID_TGV.inc()
    comptime AV_CODEC_ID_TQI = Self.AV_CODEC_ID_TGQ.inc()
    comptime AV_CODEC_ID_AURA = Self.AV_CODEC_ID_TQI.inc()
    comptime AV_CODEC_ID_AURA2 = Self.AV_CODEC_ID_AURA.inc()
    comptime AV_CODEC_ID_V210X = Self.AV_CODEC_ID_AURA2.inc()
    comptime AV_CODEC_ID_TMV = Self.AV_CODEC_ID_V210X.inc()
    comptime AV_CODEC_ID_V210 = Self.AV_CODEC_ID_TMV.inc()
    comptime AV_CODEC_ID_DPX = Self.AV_CODEC_ID_V210.inc()
    comptime AV_CODEC_ID_MAD = Self.AV_CODEC_ID_DPX.inc()
    comptime AV_CODEC_ID_FRWU = Self.AV_CODEC_ID_MAD.inc()
    comptime AV_CODEC_ID_FLASHSV2 = Self.AV_CODEC_ID_FRWU.inc()
    comptime AV_CODEC_ID_CDGRAPHICS = Self.AV_CODEC_ID_FLASHSV2.inc()
    comptime AV_CODEC_ID_R210 = Self.AV_CODEC_ID_CDGRAPHICS.inc()
    comptime AV_CODEC_ID_ANM = Self.AV_CODEC_ID_R210.inc()
    comptime AV_CODEC_ID_BINKVIDEO = Self.AV_CODEC_ID_ANM.inc()
    comptime AV_CODEC_ID_IFF_ILBM = Self.AV_CODEC_ID_BINKVIDEO.inc()
    # Was a macro:
    # define AV_CODEC_ID_IFF_BYTERUN1 AV_CODEC_ID_IFF_ILBM
    comptime AV_CODEC_ID_IFF_BYTERUN1 = Self(Self.AV_CODEC_ID_IFF_ILBM._value)

    comptime AV_CODEC_ID_KGV1 = Self.AV_CODEC_ID_IFF_BYTERUN1.inc()
    comptime AV_CODEC_ID_YOP = Self.AV_CODEC_ID_KGV1.inc()
    comptime AV_CODEC_ID_VP8 = Self.AV_CODEC_ID_YOP.inc()
    comptime AV_CODEC_ID_PICTOR = Self.AV_CODEC_ID_VP8.inc()
    comptime AV_CODEC_ID_ANSI = Self.AV_CODEC_ID_PICTOR.inc()
    comptime AV_CODEC_ID_A64_MULTI = Self.AV_CODEC_ID_ANSI.inc()
    comptime AV_CODEC_ID_A64_MULTI5 = Self.AV_CODEC_ID_A64_MULTI.inc()
    comptime AV_CODEC_ID_R10K = Self.AV_CODEC_ID_A64_MULTI5.inc()
    comptime AV_CODEC_ID_MXPEG = Self.AV_CODEC_ID_R10K.inc()
    comptime AV_CODEC_ID_LAGARITH = Self.AV_CODEC_ID_MXPEG.inc()
    comptime AV_CODEC_ID_PRORES = Self.AV_CODEC_ID_LAGARITH.inc()
    comptime AV_CODEC_ID_JV = Self.AV_CODEC_ID_PRORES.inc()
    comptime AV_CODEC_ID_DFA = Self.AV_CODEC_ID_JV.inc()
    comptime AV_CODEC_ID_WMV3IMAGE = Self.AV_CODEC_ID_DFA.inc()
    comptime AV_CODEC_ID_VC1IMAGE = Self.AV_CODEC_ID_WMV3IMAGE.inc()
    comptime AV_CODEC_ID_UTVIDEO = Self.AV_CODEC_ID_VC1IMAGE.inc()
    comptime AV_CODEC_ID_BMV_VIDEO = Self.AV_CODEC_ID_UTVIDEO.inc()
    comptime AV_CODEC_ID_VBLE = Self.AV_CODEC_ID_BMV_VIDEO.inc()
    comptime AV_CODEC_ID_DXTORY = Self.AV_CODEC_ID_VBLE.inc()

    # Handles macro inclusion of FF_API_V408_CODECID
    # if FF_API_V408_CODECID
    comptime AV_CODEC_ID_V410 = Self.xor(
        Self.AV_CODEC_ID_DXTORY._value + 1, 0, FF_API_V408_CODECID
    )

    comptime AV_CODEC_ID_XWD = Self.xor(
        Self.AV_CODEC_ID_V410._value + 1,
        0,
        FF_API_V408_CODECID,
    )
    comptime AV_CODEC_ID_CDXL = Self.AV_CODEC_ID_XWD.inc()
    comptime AV_CODEC_ID_XBM = Self.AV_CODEC_ID_CDXL.inc()
    comptime AV_CODEC_ID_ZEROCODEC = Self.AV_CODEC_ID_XBM.inc()
    comptime AV_CODEC_ID_MSS1 = Self.AV_CODEC_ID_ZEROCODEC.inc()
    comptime AV_CODEC_ID_MSA1 = Self.AV_CODEC_ID_MSS1.inc()
    comptime AV_CODEC_ID_TSCC2 = Self.AV_CODEC_ID_MSA1.inc()
    comptime AV_CODEC_ID_MTS2 = Self.AV_CODEC_ID_TSCC2.inc()
    comptime AV_CODEC_ID_CLLC = Self.AV_CODEC_ID_MTS2.inc()
    comptime AV_CODEC_ID_MSS2 = Self.AV_CODEC_ID_CLLC.inc()
    comptime AV_CODEC_ID_VP9 = Self.AV_CODEC_ID_MSS2.inc()
    comptime AV_CODEC_ID_AIC = Self.AV_CODEC_ID_VP9.inc()
    comptime AV_CODEC_ID_ESCAPE130 = Self.AV_CODEC_ID_AIC.inc()
    comptime AV_CODEC_ID_G2M = Self.AV_CODEC_ID_ESCAPE130.inc()
    comptime AV_CODEC_ID_WEBP = Self.AV_CODEC_ID_G2M.inc()
    comptime AV_CODEC_ID_HNM4_VIDEO = Self.AV_CODEC_ID_WEBP.inc()
    comptime AV_CODEC_ID_HEVC = Self.AV_CODEC_ID_HNM4_VIDEO.inc()
    # Was a macro:
    # define AV_CODEC_ID_H265 AV_CODEC_ID_HEVC
    comptime AV_CODEC_ID_H265 = Self(Self.AV_CODEC_ID_HEVC._value)

    comptime AV_CODEC_ID_FIC = Self.AV_CODEC_ID_H265.inc()
    comptime AV_CODEC_ID_ALIAS_PIX = Self.AV_CODEC_ID_FIC.inc()
    comptime AV_CODEC_ID_BRENDER_PIX = Self.AV_CODEC_ID_ALIAS_PIX.inc()
    comptime AV_CODEC_ID_PAF_VIDEO = Self.AV_CODEC_ID_BRENDER_PIX.inc()
    comptime AV_CODEC_ID_EXR = Self.AV_CODEC_ID_PAF_VIDEO.inc()
    comptime AV_CODEC_ID_VP7 = Self.AV_CODEC_ID_EXR.inc()
    comptime AV_CODEC_ID_SANM = Self.AV_CODEC_ID_VP7.inc()
    comptime AV_CODEC_ID_SGIRLE = Self.AV_CODEC_ID_SANM.inc()
    comptime AV_CODEC_ID_MVC1 = Self.AV_CODEC_ID_SGIRLE.inc()
    comptime AV_CODEC_ID_MVC2 = Self.AV_CODEC_ID_MVC1.inc()
    comptime AV_CODEC_ID_HQX = Self.AV_CODEC_ID_MVC2.inc()
    comptime AV_CODEC_ID_TDSC = Self.AV_CODEC_ID_HQX.inc()
    comptime AV_CODEC_ID_HQ_HQA = Self.AV_CODEC_ID_TDSC.inc()
    comptime AV_CODEC_ID_HAP = Self.AV_CODEC_ID_HQ_HQA.inc()
    comptime AV_CODEC_ID_DDS = Self.AV_CODEC_ID_HAP.inc()
    comptime AV_CODEC_ID_DXV = Self.AV_CODEC_ID_DDS.inc()
    comptime AV_CODEC_ID_SCREENPRESSO = Self.AV_CODEC_ID_DXV.inc()
    comptime AV_CODEC_ID_RSCC = Self.AV_CODEC_ID_SCREENPRESSO.inc()
    comptime AV_CODEC_ID_AVS2 = Self.AV_CODEC_ID_RSCC.inc()
    comptime AV_CODEC_ID_PGX = Self.AV_CODEC_ID_AVS2.inc()
    comptime AV_CODEC_ID_AVS3 = Self.AV_CODEC_ID_PGX.inc()
    comptime AV_CODEC_ID_MSP2 = Self.AV_CODEC_ID_AVS3.inc()
    comptime AV_CODEC_ID_VVC = Self.AV_CODEC_ID_MSP2.inc()

    # Was macro
    # define AV_CODEC_ID_H266 AV_CODEC_ID_VVC
    comptime AV_CODEC_ID_H266 = Self(Self.AV_CODEC_ID_VVC._value)

    comptime AV_CODEC_ID_Y41P = Self.AV_CODEC_ID_H266.inc()
    comptime AV_CODEC_ID_AVRP = Self.AV_CODEC_ID_Y41P.inc()
    comptime AV_CODEC_ID_012V = Self.AV_CODEC_ID_AVRP.inc()
    comptime AV_CODEC_ID_AVUI = Self.AV_CODEC_ID_012V.inc()
    comptime AV_CODEC_ID_TARGA_Y216 = Self.AV_CODEC_ID_AVUI.inc()

    # Was macro for these 2 fields being toggled on and off.
    # if FF_API_V408_CODECID
    comptime AV_CODEC_ID_V308 = Self.xor(
        Self.AV_CODEC_ID_TARGA_Y216._value + 1, 0, FF_API_V408_CODECID
    )
    comptime AV_CODEC_ID_V408 = Self.xor(
        Self.AV_CODEC_ID_V308._value + 1, 0, FF_API_V408_CODECID
    )

    comptime AV_CODEC_ID_YUV4 = Self.xor(
        Self.AV_CODEC_ID_V408._value + 1,
        Self.AV_CODEC_ID_TARGA_Y216._value + 1,
        FF_API_V408_CODECID,
    )
    comptime AV_CODEC_ID_AVRN = Self.AV_CODEC_ID_YUV4.inc()
    comptime AV_CODEC_ID_CPIA = Self.AV_CODEC_ID_AVRN.inc()
    comptime AV_CODEC_ID_XFACE = Self.AV_CODEC_ID_CPIA.inc()
    comptime AV_CODEC_ID_SNOW = Self.AV_CODEC_ID_XFACE.inc()
    comptime AV_CODEC_ID_SMVJPEG = Self.AV_CODEC_ID_SNOW.inc()
    comptime AV_CODEC_ID_APNG = Self.AV_CODEC_ID_SMVJPEG.inc()
    comptime AV_CODEC_ID_DAALA = Self.AV_CODEC_ID_APNG.inc()
    comptime AV_CODEC_ID_CFHD = Self.AV_CODEC_ID_DAALA.inc()
    comptime AV_CODEC_ID_TRUEMOTION2RT = Self.AV_CODEC_ID_CFHD.inc()
    comptime AV_CODEC_ID_M101 = Self.AV_CODEC_ID_TRUEMOTION2RT.inc()
    comptime AV_CODEC_ID_MAGICYUV = Self.AV_CODEC_ID_M101.inc()
    comptime AV_CODEC_ID_SHEERVIDEO = Self.AV_CODEC_ID_MAGICYUV.inc()
    comptime AV_CODEC_ID_YLC = Self.AV_CODEC_ID_SHEERVIDEO.inc()
    comptime AV_CODEC_ID_PSD = Self.AV_CODEC_ID_YLC.inc()
    comptime AV_CODEC_ID_PIXLET = Self.AV_CODEC_ID_PSD.inc()
    comptime AV_CODEC_ID_SPEEDHQ = Self.AV_CODEC_ID_PIXLET.inc()
    comptime AV_CODEC_ID_FMVC = Self.AV_CODEC_ID_SPEEDHQ.inc()
    comptime AV_CODEC_ID_SCPR = Self.AV_CODEC_ID_FMVC.inc()
    comptime AV_CODEC_ID_CLEARVIDEO = Self.AV_CODEC_ID_SCPR.inc()
    comptime AV_CODEC_ID_XPM = Self.AV_CODEC_ID_CLEARVIDEO.inc()
    comptime AV_CODEC_ID_AV1 = Self.AV_CODEC_ID_XPM.inc()
    comptime AV_CODEC_ID_BITPACKED = Self.AV_CODEC_ID_AV1.inc()
    comptime AV_CODEC_ID_MSCC = Self.AV_CODEC_ID_BITPACKED.inc()
    comptime AV_CODEC_ID_SRGC = Self.AV_CODEC_ID_MSCC.inc()
    comptime AV_CODEC_ID_SVG = Self.AV_CODEC_ID_SRGC.inc()
    comptime AV_CODEC_ID_GDV = Self.AV_CODEC_ID_SVG.inc()
    comptime AV_CODEC_ID_FITS = Self.AV_CODEC_ID_GDV.inc()
    comptime AV_CODEC_ID_IMM4 = Self.AV_CODEC_ID_FITS.inc()
    comptime AV_CODEC_ID_PROSUMER = Self.AV_CODEC_ID_IMM4.inc()
    comptime AV_CODEC_ID_MWSC = Self.AV_CODEC_ID_PROSUMER.inc()
    comptime AV_CODEC_ID_WCMV = Self.AV_CODEC_ID_MWSC.inc()
    comptime AV_CODEC_ID_RASC = Self.AV_CODEC_ID_WCMV.inc()
    comptime AV_CODEC_ID_HYMT = Self.AV_CODEC_ID_RASC.inc()
    comptime AV_CODEC_ID_ARBC = Self.AV_CODEC_ID_HYMT.inc()
    comptime AV_CODEC_ID_AGM = Self.AV_CODEC_ID_ARBC.inc()
    comptime AV_CODEC_ID_LSCR = Self.AV_CODEC_ID_AGM.inc()
    comptime AV_CODEC_ID_VP4 = Self.AV_CODEC_ID_LSCR.inc()
    comptime AV_CODEC_ID_IMM5 = Self.AV_CODEC_ID_VP4.inc()
    comptime AV_CODEC_ID_MVDV = Self.AV_CODEC_ID_IMM5.inc()
    comptime AV_CODEC_ID_MVHA = Self.AV_CODEC_ID_MVDV.inc()
    comptime AV_CODEC_ID_CDTOONS = Self.AV_CODEC_ID_MVHA.inc()
    comptime AV_CODEC_ID_MV30 = Self.AV_CODEC_ID_CDTOONS.inc()
    comptime AV_CODEC_ID_NOTCHLC = Self.AV_CODEC_ID_MV30.inc()
    comptime AV_CODEC_ID_PFM = Self.AV_CODEC_ID_NOTCHLC.inc()
    comptime AV_CODEC_ID_MOBICLIP = Self.AV_CODEC_ID_PFM.inc()
    comptime AV_CODEC_ID_PHOTOCD = Self.AV_CODEC_ID_MOBICLIP.inc()
    comptime AV_CODEC_ID_IPU = Self.AV_CODEC_ID_PHOTOCD.inc()
    comptime AV_CODEC_ID_ARGO = Self.AV_CODEC_ID_IPU.inc()
    comptime AV_CODEC_ID_CRI = Self.AV_CODEC_ID_ARGO.inc()
    comptime AV_CODEC_ID_SIMBIOSIS_IMX = Self.AV_CODEC_ID_CRI.inc()
    comptime AV_CODEC_ID_SGA_VIDEO = Self.AV_CODEC_ID_SIMBIOSIS_IMX.inc()
    comptime AV_CODEC_ID_GEM = Self.AV_CODEC_ID_SGA_VIDEO.inc()
    comptime AV_CODEC_ID_VBN = Self.AV_CODEC_ID_GEM.inc()
    comptime AV_CODEC_ID_JPEGXL = Self.AV_CODEC_ID_VBN.inc()
    comptime AV_CODEC_ID_QOI = Self.AV_CODEC_ID_JPEGXL.inc()
    comptime AV_CODEC_ID_PHM = Self.AV_CODEC_ID_QOI.inc()
    comptime AV_CODEC_ID_RADIANCE_HDR = Self.AV_CODEC_ID_PHM.inc()
    comptime AV_CODEC_ID_WBMP = Self.AV_CODEC_ID_RADIANCE_HDR.inc()
    comptime AV_CODEC_ID_MEDIA100 = Self.AV_CODEC_ID_WBMP.inc()
    comptime AV_CODEC_ID_VQC = Self.AV_CODEC_ID_MEDIA100.inc()
    comptime AV_CODEC_ID_PDV = Self.AV_CODEC_ID_VQC.inc()
    comptime AV_CODEC_ID_EVC = Self.AV_CODEC_ID_PDV.inc()
    comptime AV_CODEC_ID_RTV1 = Self.AV_CODEC_ID_EVC.inc()
    comptime AV_CODEC_ID_VMIX = Self.AV_CODEC_ID_RTV1.inc()
    comptime AV_CODEC_ID_LEAD = Self.AV_CODEC_ID_VMIX.inc()
    comptime AV_CODEC_ID_DNXUC = Self.AV_CODEC_ID_LEAD.inc()
    comptime AV_CODEC_ID_RV60 = Self.AV_CODEC_ID_DNXUC.inc()
    comptime AV_CODEC_ID_JPEGXL_ANIM = Self.AV_CODEC_ID_RV60.inc()
    comptime AV_CODEC_ID_APV = Self.AV_CODEC_ID_JPEGXL_ANIM.inc()
    comptime AV_CODEC_ID_PRORES_RAW = Self.AV_CODEC_ID_APV.inc()

    # various PCM "codecs"
    # These start at 65536.
    # < A dummy id pointing at the start of audio codecs
    comptime AV_CODEC_ID_FIRST_AUDIO = Self(0x10000)
    comptime AV_CODEC_ID_PCM_S16LE = Self(0x10000)
    comptime AV_CODEC_ID_PCM_S16BE = Self.AV_CODEC_ID_PCM_S16LE.inc()
    comptime AV_CODEC_ID_PCM_U16LE = Self.AV_CODEC_ID_PCM_S16BE.inc()
    comptime AV_CODEC_ID_PCM_U16BE = Self.AV_CODEC_ID_PCM_U16LE.inc()
    comptime AV_CODEC_ID_PCM_S8 = Self.AV_CODEC_ID_PCM_U16BE.inc()
    comptime AV_CODEC_ID_PCM_U8 = Self.AV_CODEC_ID_PCM_S8.inc()
    comptime AV_CODEC_ID_PCM_MULAW = Self.AV_CODEC_ID_PCM_U8.inc()
    comptime AV_CODEC_ID_PCM_ALAW = Self.AV_CODEC_ID_PCM_MULAW.inc()
    comptime AV_CODEC_ID_PCM_S32LE = Self.AV_CODEC_ID_PCM_ALAW.inc()
    comptime AV_CODEC_ID_PCM_S32BE = Self.AV_CODEC_ID_PCM_S32LE.inc()
    comptime AV_CODEC_ID_PCM_U32LE = Self.AV_CODEC_ID_PCM_S32BE.inc()
    comptime AV_CODEC_ID_PCM_U32BE = Self.AV_CODEC_ID_PCM_U32LE.inc()
    comptime AV_CODEC_ID_PCM_S24LE = Self.AV_CODEC_ID_PCM_U32BE.inc()
    comptime AV_CODEC_ID_PCM_S24BE = Self.AV_CODEC_ID_PCM_S24LE.inc()
    comptime AV_CODEC_ID_PCM_U24LE = Self.AV_CODEC_ID_PCM_S24BE.inc()
    comptime AV_CODEC_ID_PCM_U24BE = Self.AV_CODEC_ID_PCM_U24LE.inc()
    comptime AV_CODEC_ID_PCM_S24DAUD = Self.AV_CODEC_ID_PCM_U24BE.inc()
    comptime AV_CODEC_ID_PCM_ZORK = Self.AV_CODEC_ID_PCM_S24DAUD.inc()
    comptime AV_CODEC_ID_PCM_S16LE_PLANAR = Self.AV_CODEC_ID_PCM_ZORK.inc()
    comptime AV_CODEC_ID_PCM_DVD = Self.AV_CODEC_ID_PCM_S16LE_PLANAR.inc()
    comptime AV_CODEC_ID_PCM_F32BE = Self.AV_CODEC_ID_PCM_DVD.inc()
    comptime AV_CODEC_ID_PCM_F32LE = Self.AV_CODEC_ID_PCM_F32BE.inc()
    comptime AV_CODEC_ID_PCM_F64BE = Self.AV_CODEC_ID_PCM_F32LE.inc()
    comptime AV_CODEC_ID_PCM_F64LE = Self.AV_CODEC_ID_PCM_F64BE.inc()
    comptime AV_CODEC_ID_PCM_BLURAY = Self.AV_CODEC_ID_PCM_F64LE.inc()
    comptime AV_CODEC_ID_PCM_LXF = Self.AV_CODEC_ID_PCM_BLURAY.inc()
    comptime AV_CODEC_ID_S302M = Self.AV_CODEC_ID_PCM_LXF.inc()
    comptime AV_CODEC_ID_PCM_S8_PLANAR = Self.AV_CODEC_ID_S302M.inc()
    comptime AV_CODEC_ID_PCM_S24LE_PLANAR = Self.AV_CODEC_ID_PCM_S8_PLANAR.inc()
    comptime AV_CODEC_ID_PCM_S32LE_PLANAR = Self.AV_CODEC_ID_PCM_S24LE_PLANAR.inc()
    comptime AV_CODEC_ID_PCM_S16BE_PLANAR = Self.AV_CODEC_ID_PCM_S32LE_PLANAR.inc()
    comptime AV_CODEC_ID_PCM_S64LE = Self.AV_CODEC_ID_PCM_S16BE_PLANAR.inc()
    comptime AV_CODEC_ID_PCM_S64BE = Self.AV_CODEC_ID_PCM_S64LE.inc()
    comptime AV_CODEC_ID_PCM_F16LE = Self.AV_CODEC_ID_PCM_S64BE.inc()
    comptime AV_CODEC_ID_PCM_F24LE = Self.AV_CODEC_ID_PCM_F16LE.inc()
    comptime AV_CODEC_ID_PCM_VIDC = Self.AV_CODEC_ID_PCM_F24LE.inc()
    comptime AV_CODEC_ID_PCM_SGA = Self.AV_CODEC_ID_PCM_VIDC.inc()

    # various ADPCM codecs
    # Starts at 69632
    comptime AV_CODEC_ID_ADPCM_IMA_QT = Self(0x11000)
    comptime AV_CODEC_ID_ADPCM_IMA_WAV = Self.AV_CODEC_ID_ADPCM_IMA_QT.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_DK3 = Self.AV_CODEC_ID_ADPCM_IMA_WAV.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_DK4 = Self.AV_CODEC_ID_ADPCM_IMA_DK3.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_WS = Self.AV_CODEC_ID_ADPCM_IMA_DK4.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_SMJPEG = Self.AV_CODEC_ID_ADPCM_IMA_WS.inc()
    comptime AV_CODEC_ID_ADPCM_MS = Self.AV_CODEC_ID_ADPCM_IMA_SMJPEG.inc()
    comptime AV_CODEC_ID_ADPCM_4XM = Self.AV_CODEC_ID_ADPCM_MS.inc()
    comptime AV_CODEC_ID_ADPCM_XA = Self.AV_CODEC_ID_ADPCM_4XM.inc()
    comptime AV_CODEC_ID_ADPCM_ADX = Self.AV_CODEC_ID_ADPCM_XA.inc()
    comptime AV_CODEC_ID_ADPCM_EA = Self.AV_CODEC_ID_ADPCM_ADX.inc()
    comptime AV_CODEC_ID_ADPCM_G726 = Self.AV_CODEC_ID_ADPCM_EA.inc()
    comptime AV_CODEC_ID_ADPCM_CT = Self.AV_CODEC_ID_ADPCM_G726.inc()
    comptime AV_CODEC_ID_ADPCM_SWF = Self.AV_CODEC_ID_ADPCM_CT.inc()
    comptime AV_CODEC_ID_ADPCM_YAMAHA = Self.AV_CODEC_ID_ADPCM_SWF.inc()
    comptime AV_CODEC_ID_ADPCM_SBPRO_4 = Self.AV_CODEC_ID_ADPCM_YAMAHA.inc()
    comptime AV_CODEC_ID_ADPCM_SBPRO_3 = Self.AV_CODEC_ID_ADPCM_SBPRO_4.inc()
    comptime AV_CODEC_ID_ADPCM_SBPRO_2 = Self.AV_CODEC_ID_ADPCM_SBPRO_3.inc()
    comptime AV_CODEC_ID_ADPCM_THP = Self.AV_CODEC_ID_ADPCM_SBPRO_2.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_AMV = Self.AV_CODEC_ID_ADPCM_THP.inc()
    comptime AV_CODEC_ID_ADPCM_EA_R1 = Self.AV_CODEC_ID_ADPCM_IMA_AMV.inc()
    comptime AV_CODEC_ID_ADPCM_EA_R3 = Self.AV_CODEC_ID_ADPCM_EA_R1.inc()
    comptime AV_CODEC_ID_ADPCM_EA_R2 = Self.AV_CODEC_ID_ADPCM_EA_R3.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_EA_SEAD = Self.AV_CODEC_ID_ADPCM_EA_R2.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_EA_EACS = Self.AV_CODEC_ID_ADPCM_IMA_EA_SEAD.inc()
    comptime AV_CODEC_ID_ADPCM_EA_XAS = Self.AV_CODEC_ID_ADPCM_IMA_EA_EACS.inc()
    comptime AV_CODEC_ID_ADPCM_EA_MAXIS_XA = Self.AV_CODEC_ID_ADPCM_EA_XAS.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_ISS = Self.AV_CODEC_ID_ADPCM_EA_MAXIS_XA.inc()
    comptime AV_CODEC_ID_ADPCM_G722 = Self.AV_CODEC_ID_ADPCM_IMA_ISS.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_APC = Self.AV_CODEC_ID_ADPCM_G722.inc()
    comptime AV_CODEC_ID_ADPCM_VIMA = Self.AV_CODEC_ID_ADPCM_IMA_APC.inc()
    comptime AV_CODEC_ID_ADPCM_AFC = Self.AV_CODEC_ID_ADPCM_VIMA.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_OKI = Self.AV_CODEC_ID_ADPCM_AFC.inc()
    comptime AV_CODEC_ID_ADPCM_DTK = Self.AV_CODEC_ID_ADPCM_IMA_OKI.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_RAD = Self.AV_CODEC_ID_ADPCM_DTK.inc()
    comptime AV_CODEC_ID_ADPCM_G726LE = Self.AV_CODEC_ID_ADPCM_IMA_RAD.inc()
    comptime AV_CODEC_ID_ADPCM_THP_LE = Self.AV_CODEC_ID_ADPCM_G726LE.inc()
    comptime AV_CODEC_ID_ADPCM_PSX = Self.AV_CODEC_ID_ADPCM_THP_LE.inc()
    comptime AV_CODEC_ID_ADPCM_AICA = Self.AV_CODEC_ID_ADPCM_PSX.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_DAT4 = Self.AV_CODEC_ID_ADPCM_AICA.inc()
    comptime AV_CODEC_ID_ADPCM_MTAF = Self.AV_CODEC_ID_ADPCM_IMA_DAT4.inc()
    comptime AV_CODEC_ID_ADPCM_AGM = Self.AV_CODEC_ID_ADPCM_MTAF.inc()
    comptime AV_CODEC_ID_ADPCM_ARGO = Self.AV_CODEC_ID_ADPCM_AGM.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_SSI = Self.AV_CODEC_ID_ADPCM_ARGO.inc()
    comptime AV_CODEC_ID_ADPCM_ZORK = Self.AV_CODEC_ID_ADPCM_IMA_SSI.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_APM = Self.AV_CODEC_ID_ADPCM_ZORK.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_ALP = Self.AV_CODEC_ID_ADPCM_IMA_APM.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_MTF = Self.AV_CODEC_ID_ADPCM_IMA_ALP.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_CUNNING = Self.AV_CODEC_ID_ADPCM_IMA_MTF.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_MOFLEX = Self.AV_CODEC_ID_ADPCM_IMA_CUNNING.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_ACORN = Self.AV_CODEC_ID_ADPCM_IMA_MOFLEX.inc()
    comptime AV_CODEC_ID_ADPCM_XMD = Self.AV_CODEC_ID_ADPCM_IMA_ACORN.inc()
    comptime AV_CODEC_ID_ADPCM_IMA_XBOX = Self.AV_CODEC_ID_ADPCM_XMD.inc()
    comptime AV_CODEC_ID_ADPCM_SANYO = Self.AV_CODEC_ID_ADPCM_IMA_XBOX.inc()

    # AMR
    comptime AV_CODEC_ID_AMR_NB = Self(0x12000)
    comptime AV_CODEC_ID_AMR_WB = Self.AV_CODEC_ID_AMR_NB.inc()

    # RealAudio codecs
    comptime AV_CODEC_ID_RA_144 = Self(0x13000)
    comptime AV_CODEC_ID_RA_288 = Self.AV_CODEC_ID_RA_144.inc()

    # various DPCM codecs
    comptime AV_CODEC_ID_ROQ_DPCM = Self(0x14000)
    comptime AV_CODEC_ID_INTERPLAY_DPCM = Self.AV_CODEC_ID_ROQ_DPCM.inc()
    comptime AV_CODEC_ID_XAN_DPCM = Self.AV_CODEC_ID_INTERPLAY_DPCM.inc()
    comptime AV_CODEC_ID_SOL_DPCM = Self.AV_CODEC_ID_XAN_DPCM.inc()
    comptime AV_CODEC_ID_SDX2_DPCM = Self.AV_CODEC_ID_SOL_DPCM.inc()
    comptime AV_CODEC_ID_GREMLIN_DPCM = Self.AV_CODEC_ID_SDX2_DPCM.inc()
    comptime AV_CODEC_ID_DERF_DPCM = Self.AV_CODEC_ID_GREMLIN_DPCM.inc()
    comptime AV_CODEC_ID_WADY_DPCM = Self.AV_CODEC_ID_DERF_DPCM.inc()
    comptime AV_CODEC_ID_CBD2_DPCM = Self.AV_CODEC_ID_WADY_DPCM.inc()

    # audio codecs
    comptime AV_CODEC_ID_MP2 = Self(0x15000)

    # < preferred ID for decoding MPEG audio layer 1, 2 or 3
    comptime AV_CODEC_ID_MP3 = Self.AV_CODEC_ID_MP2.inc()
    comptime AV_CODEC_ID_AAC = Self.AV_CODEC_ID_MP3.inc()
    comptime AV_CODEC_ID_AC3 = Self.AV_CODEC_ID_AAC.inc()
    comptime AV_CODEC_ID_DTS = Self.AV_CODEC_ID_AC3.inc()
    comptime AV_CODEC_ID_VORBIS = Self.AV_CODEC_ID_DTS.inc()
    comptime AV_CODEC_ID_DVAUDIO = Self.AV_CODEC_ID_VORBIS.inc()
    comptime AV_CODEC_ID_WMAV1 = Self.AV_CODEC_ID_DVAUDIO.inc()
    comptime AV_CODEC_ID_WMAV2 = Self.AV_CODEC_ID_WMAV1.inc()
    comptime AV_CODEC_ID_MACE3 = Self.AV_CODEC_ID_WMAV2.inc()
    comptime AV_CODEC_ID_MACE6 = Self.AV_CODEC_ID_MACE3.inc()
    comptime AV_CODEC_ID_VMDAUDIO = Self.AV_CODEC_ID_MACE6.inc()
    comptime AV_CODEC_ID_FLAC = Self.AV_CODEC_ID_VMDAUDIO.inc()
    comptime AV_CODEC_ID_MP3ADU = Self.AV_CODEC_ID_FLAC.inc()
    comptime AV_CODEC_ID_MP3ON4 = Self.AV_CODEC_ID_MP3ADU.inc()
    comptime AV_CODEC_ID_SHORTEN = Self.AV_CODEC_ID_MP3ON4.inc()
    comptime AV_CODEC_ID_ALAC = Self.AV_CODEC_ID_SHORTEN.inc()
    comptime AV_CODEC_ID_WESTWOOD_SND1 = Self.AV_CODEC_ID_ALAC.inc()

    # < as in Berlin toast format
    comptime AV_CODEC_ID_GSM = Self.AV_CODEC_ID_WESTWOOD_SND1.inc()
    comptime AV_CODEC_ID_QDM2 = Self.AV_CODEC_ID_GSM.inc()
    comptime AV_CODEC_ID_COOK = Self.AV_CODEC_ID_QDM2.inc()
    comptime AV_CODEC_ID_TRUESPEECH = Self.AV_CODEC_ID_COOK.inc()
    comptime AV_CODEC_ID_TTA = Self.AV_CODEC_ID_TRUESPEECH.inc()
    comptime AV_CODEC_ID_SMACKAUDIO = Self.AV_CODEC_ID_TTA.inc()
    comptime AV_CODEC_ID_QCELP = Self.AV_CODEC_ID_SMACKAUDIO.inc()
    comptime AV_CODEC_ID_WAVPACK = Self.AV_CODEC_ID_QCELP.inc()
    comptime AV_CODEC_ID_DSICINAUDIO = Self.AV_CODEC_ID_WAVPACK.inc()
    comptime AV_CODEC_ID_IMC = Self.AV_CODEC_ID_DSICINAUDIO.inc()
    comptime AV_CODEC_ID_MUSEPACK7 = Self.AV_CODEC_ID_IMC.inc()
    comptime AV_CODEC_ID_MLP = Self.AV_CODEC_ID_MUSEPACK7.inc()
    comptime AV_CODEC_ID_GSM_MS = Self.AV_CODEC_ID_MLP.inc()  # as found in WAV
    comptime AV_CODEC_ID_ATRAC3 = Self.AV_CODEC_ID_GSM_MS.inc()
    comptime AV_CODEC_ID_APE = Self.AV_CODEC_ID_ATRAC3.inc()
    comptime AV_CODEC_ID_NELLYMOSER = Self.AV_CODEC_ID_APE.inc()
    comptime AV_CODEC_ID_MUSEPACK8 = Self.AV_CODEC_ID_NELLYMOSER.inc()
    comptime AV_CODEC_ID_SPEEX = Self.AV_CODEC_ID_MUSEPACK8.inc()
    comptime AV_CODEC_ID_WMAVOICE = Self.AV_CODEC_ID_SPEEX.inc()
    comptime AV_CODEC_ID_WMAPRO = Self.AV_CODEC_ID_WMAVOICE.inc()
    comptime AV_CODEC_ID_WMALOSSLESS = Self.AV_CODEC_ID_WMAPRO.inc()
    comptime AV_CODEC_ID_ATRAC3P = Self.AV_CODEC_ID_WMALOSSLESS.inc()
    comptime AV_CODEC_ID_EAC3 = Self.AV_CODEC_ID_ATRAC3P.inc()
    comptime AV_CODEC_ID_SIPR = Self.AV_CODEC_ID_EAC3.inc()
    comptime AV_CODEC_ID_MP1 = Self.AV_CODEC_ID_SIPR.inc()
    comptime AV_CODEC_ID_TWINVQ = Self.AV_CODEC_ID_MP1.inc()
    comptime AV_CODEC_ID_TRUEHD = Self.AV_CODEC_ID_TWINVQ.inc()
    comptime AV_CODEC_ID_MP4ALS = Self.AV_CODEC_ID_TRUEHD.inc()
    comptime AV_CODEC_ID_ATRAC1 = Self.AV_CODEC_ID_MP4ALS.inc()
    comptime AV_CODEC_ID_BINKAUDIO_RDFT = Self.AV_CODEC_ID_ATRAC1.inc()
    comptime AV_CODEC_ID_BINKAUDIO_DCT = Self.AV_CODEC_ID_BINKAUDIO_RDFT.inc()
    comptime AV_CODEC_ID_AAC_LATM = Self.AV_CODEC_ID_BINKAUDIO_DCT.inc()
    comptime AV_CODEC_ID_QDMC = Self.AV_CODEC_ID_AAC_LATM.inc()
    comptime AV_CODEC_ID_CELT = Self.AV_CODEC_ID_QDMC.inc()
    comptime AV_CODEC_ID_G723_1 = Self.AV_CODEC_ID_CELT.inc()
    comptime AV_CODEC_ID_G729 = Self.AV_CODEC_ID_G723_1.inc()
    comptime AV_CODEC_ID_8SVX_EXP = Self.AV_CODEC_ID_G729.inc()
    comptime AV_CODEC_ID_8SVX_FIB = Self.AV_CODEC_ID_8SVX_EXP.inc()
    comptime AV_CODEC_ID_BMV_AUDIO = Self.AV_CODEC_ID_8SVX_FIB.inc()
    comptime AV_CODEC_ID_RALF = Self.AV_CODEC_ID_BMV_AUDIO.inc()
    comptime AV_CODEC_ID_IAC = Self.AV_CODEC_ID_RALF.inc()
    comptime AV_CODEC_ID_ILBC = Self.AV_CODEC_ID_IAC.inc()
    comptime AV_CODEC_ID_OPUS = Self.AV_CODEC_ID_ILBC.inc()
    comptime AV_CODEC_ID_COMFORT_NOISE = Self.AV_CODEC_ID_OPUS.inc()
    comptime AV_CODEC_ID_TAK = Self.AV_CODEC_ID_COMFORT_NOISE.inc()
    comptime AV_CODEC_ID_METASOUND = Self.AV_CODEC_ID_TAK.inc()
    comptime AV_CODEC_ID_PAF_AUDIO = Self.AV_CODEC_ID_METASOUND.inc()
    comptime AV_CODEC_ID_ON2AVC = Self.AV_CODEC_ID_PAF_AUDIO.inc()
    comptime AV_CODEC_ID_DSS_SP = Self.AV_CODEC_ID_ON2AVC.inc()
    comptime AV_CODEC_ID_CODEC2 = Self.AV_CODEC_ID_DSS_SP.inc()
    comptime AV_CODEC_ID_FFWAVESYNTH = Self.AV_CODEC_ID_CODEC2.inc()
    comptime AV_CODEC_ID_SONIC = Self.AV_CODEC_ID_FFWAVESYNTH.inc()
    comptime AV_CODEC_ID_SONIC_LS = Self.AV_CODEC_ID_SONIC.inc()
    comptime AV_CODEC_ID_EVRC = Self.AV_CODEC_ID_SONIC_LS.inc()
    comptime AV_CODEC_ID_SMV = Self.AV_CODEC_ID_EVRC.inc()
    comptime AV_CODEC_ID_DSD_LSBF = Self.AV_CODEC_ID_SMV.inc()
    comptime AV_CODEC_ID_DSD_MSBF = Self.AV_CODEC_ID_DSD_LSBF.inc()
    comptime AV_CODEC_ID_DSD_LSBF_PLANAR = Self.AV_CODEC_ID_DSD_MSBF.inc()
    comptime AV_CODEC_ID_DSD_MSBF_PLANAR = Self.AV_CODEC_ID_DSD_LSBF_PLANAR.inc()
    comptime AV_CODEC_ID_4GV = Self.AV_CODEC_ID_DSD_MSBF_PLANAR.inc()
    comptime AV_CODEC_ID_INTERPLAY_ACM = Self.AV_CODEC_ID_4GV.inc()
    comptime AV_CODEC_ID_XMA1 = Self.AV_CODEC_ID_INTERPLAY_ACM.inc()
    comptime AV_CODEC_ID_XMA2 = Self.AV_CODEC_ID_XMA1.inc()
    comptime AV_CODEC_ID_DST = Self.AV_CODEC_ID_XMA2.inc()
    comptime AV_CODEC_ID_ATRAC3AL = Self.AV_CODEC_ID_DST.inc()
    comptime AV_CODEC_ID_ATRAC3PAL = Self.AV_CODEC_ID_ATRAC3AL.inc()
    comptime AV_CODEC_ID_DOLBY_E = Self.AV_CODEC_ID_ATRAC3PAL.inc()
    comptime AV_CODEC_ID_APTX = Self.AV_CODEC_ID_DOLBY_E.inc()
    comptime AV_CODEC_ID_APTX_HD = Self.AV_CODEC_ID_APTX.inc()
    comptime AV_CODEC_ID_SBC = Self.AV_CODEC_ID_APTX_HD.inc()
    comptime AV_CODEC_ID_ATRAC9 = Self.AV_CODEC_ID_SBC.inc()
    comptime AV_CODEC_ID_HCOM = Self.AV_CODEC_ID_ATRAC9.inc()
    comptime AV_CODEC_ID_ACELP_KELVIN = Self.AV_CODEC_ID_HCOM.inc()
    comptime AV_CODEC_ID_MPEGH_3D_AUDIO = Self.AV_CODEC_ID_ACELP_KELVIN.inc()
    comptime AV_CODEC_ID_SIREN = Self.AV_CODEC_ID_MPEGH_3D_AUDIO.inc()
    comptime AV_CODEC_ID_HCA = Self.AV_CODEC_ID_SIREN.inc()
    comptime AV_CODEC_ID_FASTAUDIO = Self.AV_CODEC_ID_HCA.inc()
    comptime AV_CODEC_ID_MSNSIREN = Self.AV_CODEC_ID_FASTAUDIO.inc()
    comptime AV_CODEC_ID_DFPWM = Self.AV_CODEC_ID_MSNSIREN.inc()
    comptime AV_CODEC_ID_BONK = Self.AV_CODEC_ID_DFPWM.inc()
    comptime AV_CODEC_ID_MISC4 = Self.AV_CODEC_ID_BONK.inc()
    comptime AV_CODEC_ID_APAC = Self.AV_CODEC_ID_MISC4.inc()
    comptime AV_CODEC_ID_FTR = Self.AV_CODEC_ID_APAC.inc()
    comptime AV_CODEC_ID_WAVARC = Self.AV_CODEC_ID_FTR.inc()
    comptime AV_CODEC_ID_RKA = Self.AV_CODEC_ID_WAVARC.inc()
    comptime AV_CODEC_ID_AC4 = Self.AV_CODEC_ID_RKA.inc()
    comptime AV_CODEC_ID_OSQ = Self.AV_CODEC_ID_AC4.inc()
    comptime AV_CODEC_ID_QOA = Self.AV_CODEC_ID_OSQ.inc()
    comptime AV_CODEC_ID_LC3 = Self.AV_CODEC_ID_QOA.inc()
    comptime AV_CODEC_ID_G728 = Self.AV_CODEC_ID_LC3.inc()

    # subtitle codecs
    comptime AV_CODEC_ID_FIRST_SUBTITLE = Self(
        0x17000
    )  # < A dummy ID pointing at the start of subtitle codecs.
    comptime AV_CODEC_ID_DVD_SUBTITLE = Self(0x17000)
    comptime AV_CODEC_ID_DVB_SUBTITLE = Self.AV_CODEC_ID_DVD_SUBTITLE.inc()
    comptime AV_CODEC_ID_TEXT = Self.AV_CODEC_ID_DVB_SUBTITLE.inc()  # < raw UTF-8 text
    comptime AV_CODEC_ID_XSUB = Self.AV_CODEC_ID_TEXT.inc()
    comptime AV_CODEC_ID_SSA = Self.AV_CODEC_ID_XSUB.inc()
    comptime AV_CODEC_ID_MOV_TEXT = Self.AV_CODEC_ID_SSA.inc()
    comptime AV_CODEC_ID_HDMV_PGS_SUBTITLE = Self.AV_CODEC_ID_MOV_TEXT.inc()
    comptime AV_CODEC_ID_DVB_TELETEXT = Self.AV_CODEC_ID_HDMV_PGS_SUBTITLE.inc()
    comptime AV_CODEC_ID_SRT = Self.AV_CODEC_ID_DVB_TELETEXT.inc()
    comptime AV_CODEC_ID_MICRODVD = Self.AV_CODEC_ID_SRT.inc()
    comptime AV_CODEC_ID_EIA_608 = Self.AV_CODEC_ID_MICRODVD.inc()
    comptime AV_CODEC_ID_JACOSUB = Self.AV_CODEC_ID_EIA_608.inc()
    comptime AV_CODEC_ID_SAMI = Self.AV_CODEC_ID_JACOSUB.inc()
    comptime AV_CODEC_ID_REALTEXT = Self.AV_CODEC_ID_SAMI.inc()
    comptime AV_CODEC_ID_STL = Self.AV_CODEC_ID_REALTEXT.inc()
    comptime AV_CODEC_ID_SUBVIEWER1 = Self.AV_CODEC_ID_STL.inc()
    comptime AV_CODEC_ID_SUBVIEWER = Self.AV_CODEC_ID_SUBVIEWER1.inc()
    comptime AV_CODEC_ID_SUBRIP = Self.AV_CODEC_ID_SUBVIEWER.inc()
    comptime AV_CODEC_ID_WEBVTT = Self.AV_CODEC_ID_SUBRIP.inc()
    comptime AV_CODEC_ID_MPL2 = Self.AV_CODEC_ID_WEBVTT.inc()
    comptime AV_CODEC_ID_VPLAYER = Self.AV_CODEC_ID_MPL2.inc()
    comptime AV_CODEC_ID_PJS = Self.AV_CODEC_ID_VPLAYER.inc()
    comptime AV_CODEC_ID_ASS = Self.AV_CODEC_ID_PJS.inc()
    comptime AV_CODEC_ID_HDMV_TEXT_SUBTITLE = Self.AV_CODEC_ID_ASS.inc()
    comptime AV_CODEC_ID_TTML = Self.AV_CODEC_ID_HDMV_TEXT_SUBTITLE.inc()
    comptime AV_CODEC_ID_ARIB_CAPTION = Self.AV_CODEC_ID_TTML.inc()
    comptime AV_CODEC_ID_IVTV_VBI = Self.AV_CODEC_ID_ARIB_CAPTION.inc()

    # other specific kind of codecs (generally used for attachments)
    # A dummy ID pointing at the start of various fake codecs.
    comptime AV_CODEC_ID_FIRST_UNKNOWN = Self(0x18000)
    comptime AV_CODEC_ID_TTF = Self(0x18000)
    # < Contain timestamp estimated through PCR of program stream.
    comptime AV_CODEC_ID_SCTE_35 = Self.AV_CODEC_ID_TTF.inc()
    comptime AV_CODEC_ID_EPG = Self.AV_CODEC_ID_SCTE_35.inc()
    comptime AV_CODEC_ID_BINTEXT = Self.AV_CODEC_ID_EPG.inc()
    comptime AV_CODEC_ID_XBIN = Self.AV_CODEC_ID_BINTEXT.inc()
    comptime AV_CODEC_ID_IDF = Self.AV_CODEC_ID_XBIN.inc()
    comptime AV_CODEC_ID_OTF = Self.AV_CODEC_ID_IDF.inc()
    comptime AV_CODEC_ID_SMPTE_KLV = Self.AV_CODEC_ID_OTF.inc()
    comptime AV_CODEC_ID_DVD_NAV = Self.AV_CODEC_ID_SMPTE_KLV.inc()
    comptime AV_CODEC_ID_TIMED_ID3 = Self.AV_CODEC_ID_DVD_NAV.inc()
    comptime AV_CODEC_ID_BIN_DATA = Self.AV_CODEC_ID_TIMED_ID3.inc()
    comptime AV_CODEC_ID_SMPTE_2038 = Self.AV_CODEC_ID_BIN_DATA.inc()
    comptime AV_CODEC_ID_LCEVC = Self.AV_CODEC_ID_SMPTE_2038.inc()
    comptime AV_CODEC_ID_SMPTE_436M_ANC = Self.AV_CODEC_ID_LCEVC.inc()

    # < codec_id is not known (like AV_CODEC_ID_NONE) but lavf should attempt to identify it
    comptime AV_CODEC_ID_PROBE = Self(0x19000)

    # _FAKE_ codec to indicate a raw MPEG-2 TS
    # stream (only used by libavformat)
    comptime AV_CODEC_ID_MPEG2TS = Self(0x20000)

    # < _FAKE_ codec to indicate a MPEG-4 Systems stream (only used by libavformat)
    comptime AV_CODEC_ID_MPEG4SYSTEMS = Self(0x20001)

    # < Dummy codec for streams containing only metadata information.
    comptime AV_CODEC_ID_FFMETADATA = Self(0x21000)

    # < Passthrough codec, AVFrames wrapped in AVPacket
    comptime AV_CODEC_ID_WRAPPED_AVFRAME = Self(0x21001)

    # Dummy null video codec, useful mainly for development and debugging.
    # Null encoder/decoder discard all input and never return any output.
    comptime AV_CODEC_ID_VNULL = Self.AV_CODEC_ID_WRAPPED_AVFRAME.inc()

    # Dummy null audio codec, useful mainly for development and debugging.
    # Null encoder/decoder discard all input and never return any output.
    comptime AV_CODEC_ID_ANULL = Self.AV_CODEC_ID_VNULL.inc()
